### ISSUE TITLE
Initial ToDo

### ISSUE THREAD

**Issue by willirath** [ExaESM-WP4/Containerized-Jupyter-on-HPC#1]
- [x] Add example notebook and minimal `binder/` dir.
- [x] Build with `jupyter-repo2docker` and push to dockerhub.
- [x] Show how to run with singularity.

**Comment by willirath** [comment]
Closed with #2 and #3.
